name: "GeoCARET Documentation Build"

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
  workflow_dispatch:
    branches:
      - release

env:
  # Only build on Python 3.8
  # environment variable controlling which Python versions and platforms to build wheels for, when using cibuildwheel.
  CIBW_BUILD: cp38-*
  SERVICEACCOUNT: ${{ secrets.SERVICEACCOUNT }}
  SERVICEACCOUNT_EMAIL: ${{ secrets.SERVICEACCOUNT_EMAIL }}
  
permissions:
  contents: write

jobs:

  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0   # This is required for setuptools_scm: https://github.com/pypa/setuptools_scm/issues/480

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.11'

      - name: Build docs
        # lpsolve doesn't compile on Ubuntu without building the library from source - disable for the time being.
        # This doesn't really matter for the documentation builds.
        run: |
          sudo apt install --no-install-recommends pandoc
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_doc.txt
          pip install https://github.com/SuperKogito/sphinxcontrib-pdfembed/archive/master.zip
          cd docs
          make html

      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        # deployment will only happen when the workflow is triggered by a push or pull request to the release branch
        if: github.ref == 'refs/heads/release'
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
